config/routes.rb
Rails.application.routes.draw do
  resources :artists_posts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "artists_posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/artists_post.rb
class ArtistsPost < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/artists_posts_controller.rb
class ArtistsPostsController < ApplicationController
  before_action :set_artists_post, only: %i[ show edit update destroy ]

  # GET /artists_posts or /artists_posts.json
  def index
    @artists_posts = ArtistsPost.all
  end

  # GET /artists_posts/1 or /artists_posts/1.json
  def show
  end

  # GET /artists_posts/new
  def new
    @artists_post = ArtistsPost.new
  end

  # GET /artists_posts/1/edit
  def edit
  end

  # POST /artists_posts or /artists_posts.json
  def create
    @artists_post = ArtistsPost.new(artists_post_params)

    respond_to do |format|
      if @artists_post.save
        format.html { redirect_to artists_post_url(@artists_post), notice: "Artists post was successfully created." }
        format.json { render :show, status: :created, location: @artists_post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artists_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists_posts/1 or /artists_posts/1.json
  def update
    respond_to do |format|
      if @artists_post.update(artists_post_params)
        format.html { redirect_to artists_post_url(@artists_post), notice: "Artists post was successfully updated." }
        format.json { render :show, status: :ok, location: @artists_post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artists_post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists_posts/1 or /artists_posts/1.json
  def destroy
    @artists_post.destroy!

    respond_to do |format|
      format.html { redirect_to artists_posts_url, notice: "Artists post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artists_post
      @artists_post = ArtistsPost.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artists_post_params
      params.require(:artists_post).permit(:image, :first_name, :name, :stage_name, :soundcloud_link, :description, :instagram_link, :spotify_link, :twitter_link)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_posts_helper.rb
module ArtistsPostsHelper
end

app/views/artists_posts/_artists_post.html.erb
<center>
<div id="<%= dom_id artists_post %>">

  <br>
<div class="container">
  <div class="box1">
    <br>

  <img src="<%= artists_post.image %>" alt="Change your picture, it didnt worked">

  <br>
  <br>
  <p>
    <strong>Nickname:</strong>
    <%= artists_post.stage_name %>
  </p>

  <p>
    <strong></strong>
    <%= artists_post.description %>
  </p>  

  <br>

  <h3>

<div class="embed2">
    <p>
      <strong></strong>
      <%= raw artists_post.soundcloud_link %>
    </p>
  </div>

  <div class="embed1">
    <p>
      <strong></strong>
      <%= raw artists_post.spotify_link %>
    </p>
  </div>
  </div>
</div>
<br>
    <strong>Socials</strong>
  </h3>
  <p>
  <a href="<%= artists_post.instagram_link %>">Instagram</a>
  </p>

  <p>
    <strong></strong>
    <a href="<%= artists_post.twitter_link %>">Twitter</a>
  </p>
</div>
<br>
<br>
<br>
</center>

<style>

  .box1{
    border-style: solid;
    }
  .embed1{
    margin-left: 20px;
    margin-right: 20px;
  }
  .embed2{
    margin-left: 20px;
    margin-right: 20px;
  }
  img{
    max-width: 400px;
  }
</style>

app/views/artists_posts/_form.html.erb
<%= form_with(model: artists_post) do |form| %>
  <% if artists_post.errors.any? %>
    <div style="color: red; text-align: center; font-size: 1.2em;">
      <h2><%= pluralize(artists_post.errors.count, "error") %> prohibited this artists_post from being saved:</h2>

      <ul>
        <% artists_post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div style="display: flex; flex-wrap: wrap; justify-content: space-between; align-items: center; margin: 2em; font-size: 1.2em;">

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :first_name, style: "display: block; color: black" %>
      <%= form.text_field :first_name, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :last_name, style: "display: block; color: black" %>
      <%= form.text_field :last_name, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :stage_name, style: "display: block; color: black" %>
      <%= form.text_field :stage_name, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :image, style: "display: block; color: black" %>
      <%= form.text_area :image, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :soundcloud_link, style: "display: block; color: black" %>
      <%= form.text_area :soundcloud_link, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :description, style: "display: block; color: black" %>
      <%= form.text_field :description, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :instagram_link, style: "display: block; color: black" %>
      <%= form.text_area :instagram_link, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :spotify_link, style: "display: block; color: black" %>
      <%= form.text_area :spotify_link, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="flex: 1 0 45%; margin: 1em; padding: 1em;">
      <%= form.label :twitter_link, style: "display: block; color: black" %>
      <%= form.text_area :twitter_link, style: "width: 100%; padding: 0.5em;" %>
    </div>

    <div style="width: 100%; text-align: center; margin: 1em;">
      <%= form.submit style: "padding: 1em; font-size: 1.2em;" %>
    </div>
  </div>
<% end %>

app/views/artists_posts/edit.html.erb
<h1>Editing artists post</h1>

<%= render "form", artists_post: @artists_post %>

<br>

<div>
  <%= link_to "Show this artists post", @artists_post %> |
  <%= link_to "Back to artists posts", artists_posts_path %>
</div>

app/views/artists_posts/index.html.erb
<p style="color: green"><%= notice %></p>

<center>
<h1>Different artists posts so far</h1>
</center>
<br>
<br>
<br>

<div id="artists_posts">
  <% @artists_posts.each do |artists_post| %>
    <%= render artists_post %>
    <p>
      <%= link_to "Show this artists post", artists_post %>
    </p>
  <% end %>
</div>

<%= link_to "New artists post", new_artists_post_path %>

<style>
  h1{
    font-size: 70px;
    text-decoration: underline;
  }
</style>

app/views/artists_posts/new.html.erb
<div class="new">
<center>
  <h1><b>New artists post</b></h1>
</center>
</div>

<%= render "form", artists_post: @artists_post %>

<br>

<div>
  <%= link_to "Back to artists posts", artists_posts_path %>
</div>

<style>
  .new{
    font-size: 9999px;
  }
</style>

app/views/artists_posts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @artists_post %>

<div>
  <%= link_to "Edit this artists post", edit_artists_post_path(@artists_post) %> |
  <%= link_to "Back to artists posts", artists_posts_path %>

  <%= button_to "Destroy this artists post", @artists_post, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rakifile</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">


<nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">
      <img src="https://i.ibb.co/NWZ6SK2/Frame-1.png" alt="Logo" width="30" height="24" class="d-inline-block align-text-top">
      <b>Rakifile Search</b>
    </a>
  </div>
</nav>
<br>

<style>
  img{
    height: 90px;
    width: auto;
  }
  .navbar-brand{
    font-size: 25px;
    display: flex;
    justify-content: center;
    align-items: center;
  }
</style>
  </head>

  <body>
    <%= yield %>
  </body>
  <br>
  <br>
  <footer>
      <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
        <div class="container-fluid">
          <center>
          <a class="navbar-brand" href="#">
              Copyright2024@Rakifile
          </a>
          </center>
        </div>
      </nav>
  </footer>
</html>